name: AuthTGEM
version: '${project.version}'
main: org.ezhik.authtgem.AuthTGEM
api-version: '1.20'
Author: 'Ezhik24'
website: 'https://t.me/ezhichek11'

commands:
  unregister:
    description: 'Удалить аккаунт'
    aliases:
      - 'unreg'
  setbypass:
    description: 'Bypass for Player'
  tgbc:
    description: 'Telegramm Broadcast Command'
  mcbc:
    description: 'Minecraft Broadcast Command'