name: AuthTGEM
version: '${project.version}'
main: org.ezhik.authtgem.AuthTGEM
api-version: '1.20'
Author: 'Ezhik24'
website: 'https://t.me/ezhichek11'

commands:
  setbypass:
    description: 'Bypass for Player'